#!/usr/bin/env bash
set -ex

mkdir tmp
BUILD_PREFIX=$PWD/tmp

CONFIG_OPTS=()
CONFIG_OPTS+=("CFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("CPPFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("CXXFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("LDFLAGS=-L${BUILD_PREFIX}/lib")
CONFIG_OPTS+=("PKG_CONFIG_PATH=${BUILD_PREFIX}/lib/pkgconfig")
CONFIG_OPTS+=("--prefix=${BUILD_PREFIX}")

# dep: ctap
git clone --depth 1 git://github.com/filefrog/ctap.git
( cd ctap; ./bootstrap; ./configure "${CONFIG_OPTS[@]}"; make check; make install)

# dep: libsodium
git clone --depth 1 git://github.com/jedisct1/libsodium.git
( cd libsodium; ./autogen.sh; ./configure "${CONFIG_OPTS[@]}"; make check; make install)

# dep: libzmq
git clone --depth 1 git://github.com/zeromq/libzmq.git
( cd libzmq; ./autogen.sh; ./configure "${CONFIG_OPTS[@]}" --with-libsodium=yes; make check; make install)

./bootstrap
./configure "${CONFIG_OPTS[@]}"

make
make check
make install
